### ISSUE TITLE
How to preprocess the Assembly101 dataset for action segmentation?

### ISSUE THREAD

**Issue by ddz16** [assembly-101/assembly101-annotations#1]
Such an amazing dataset! I want to use it for the temporal action segmentation task. Can you provide the repository which contains codes for the Action Segmentation benchmark of Assembly101?  Or just the preprocess code?

**Comment by assembly-101** [comment]
We are working on the temporal action segmentation repository.
We will update it on our website: https://assembly-101.github.io/
