### ISSUE TITLE
Confusion about the number of videos

### ISSUE THREAD

**Issue by ddz16** [assembly-101/assembly101-annotations#2]
In Table 2 of the paper, the videos num is **4321**
![image](https://user-images.githubusercontent.com/45875562/197090906-c75fa7ff-25f5-492e-89a7-739b19e62ed7.png)

but in the `coarse_seq_views.txt` file you provided, the video sequences num is **8070**

Is there something wrong?

**Comment by assembly-101** [comment]
Each sequence first consists of a disassembly segment and then an assembly segment. 

If you check the name of the videos in `coarse_seq_views.txt`, you will see that some of them starts with `disassembly...` and some of them starts with `assembly...` i.e. each video has been annotated separately (once for disassembly and once for assembly).

That is why the number of entries in `coarse_seq_views.txt` is almost twice the number of videos.
