### ISSUE TITLE
Confusion about the coarse-annotations

### ISSUE THREAD

**Issue by ddz16** [assembly-101/assembly101-annotations#3]
an example:   assembly_nusar-2021_action_both_9011-b06b_9011_user_id_2021-02-01_154253.txt
```
start_frame      end_frame       action
000002833	000003156	attach interior	
000003156	000004607	attach wheel	
000004607	000005151	attach turntable top	
000005151	000005613	attach hook	
000005613	000006110	attach crane arm	
000006110	000006394	attach cabin	
000006394	000006959	demonstrate functionality	
```

The start frame of the first action segment is not 0 but 2833. Does this mean that the frames 0-2832 is background?
Similarly, will there be a background after the end frame of the last action segment?

**Comment by assembly-101** [comment]
Each sequence first consists of a disassembly segment and then an assembly segment.

If you check the name of the annotation files, you will see that some of them starts with `disassembly...` and some of them starts with `assembly...` i.e. each video has been annotated separately (once for disassembly and once for assembly).

The annotations for `assembly...` generally starts from the middle of the sequence (after disassembly is done), hence it starts with non-zero frame number like the case you mentioned.
