### ISSUE TITLE
Full coarse actions release

### ISSUE THREAD

**Issue by Camillo4eyes** [assembly-101/assembly101-annotations#4]
When will the full list of coarse_actions be released?

**Comment by assembly-101** [comment]
Hi,

Our full coarse_actions have already been released.
Please check [this](https://github.com/assembly-101/assembly101-annotations/tree/main/coarse-annotations).

**Comment by Camillo4eyes** [comment]
I don't think so, in the "coarse labels" folder there are only 513 files.

Il giorno ven 2 dic 2022 alle ore 13:01 Assembly101 <
***@***.***> ha scritto:
