### ISSUE TITLE
Annotations for error detection

### ISSUE THREAD

**Issue by Shivvrat** [assembly-101/assembly101-annotations#5]
I'm not able to find the annotations for error detection in this repository. Do we need to download it from somewhere else?

**Comment by Y-Haneji** [comment]
@assembly-101 
I couldn't find them too. Do you have a plan to publish it?

**Comment by srama2512** [comment]
@assembly-101  - When do you plan to release the mistakes + corrections annotations?

**Comment by assembly-101** [comment]
We have released the cleaned annotations for mistake detection [here](https://github.com/assembly-101/assembly101-mistake-detection).
