### ISSUE TITLE
Can you explain how you extracted the 3D hand poses from the videos? 

### ISSUE THREAD

**Issue by Shivvrat** [assembly-101/assembly101-annotations#6]

**Comment by assembly-101** [comment]
Hi Shivvrat,

We use the multi-view nature of our dataset and utilize [MegATrack](https://research.facebook.com/publications/megatrack-monochrome-egocentric-articulated-hand-tracking-for-virtual-reality/) to estimate the 3D hand poses of both hands. You can refer to Sec. 3.3 of our [paper](https://openaccess.thecvf.com/content/CVPR2022/papers/Sener_Assembly101_A_Large-Scale_Multi-View_Video_Dataset_for_Understanding_Procedural_Activities_CVPR_2022_paper.pdf) for more details.
