### ISSUE TITLE
Camera intrinsic and extrinsic are not available?

### ISSUE THREAD

**Issue by zdforient** [assembly-101/assembly101-annotations#8]
Hi,

Thanks for sharing the dataset. We want to porject the hand pose back to the videos to verify if the poses are aligned with the videos. 
But we don't see the camera intrinsic and extrinsic parameters in the dataset.

Coud you upload it to the Google drive?

Thanks

**Comment by zdforient** [comment]
some parameters are available in the previous issue.

**Comment by olga-zats** [comment]
Hi!

Could you please specify where were you able to find the camera parameters? I was looking for them as well, but could not find them. 

Thanks!

**Comment by zdforient** [comment]
https://drive.google.com/drive/folders/1nNj5Z8v73brMJKBZxLjvVxJOaIMpDHUx?usp=sharing
Here are some.

**Comment by olga-zats** [comment]
Thank you!
