### ISSUE TITLE
About frame rate

### ISSUE THREAD

**Issue by Tarmo-moriwaki** [assembly-101/assembly101-annotations#9]
Thank you for providing the annotation data!
How many FPS did you handle the video data when you annotated?
When I cut frame images from video data with 60 FPS, I found a mismatch between the number of images and the annotation-end frame.

**Comment by assembly-101** [comment]
Hi,

As mentioned [here](https://github.com/assembly-101/assembly101-annotations#assembly101-annotations), the annotations are provided at 30fps.
